# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
       node-version: ${{ matrix.node-version }}
       cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: false
#    - run: npm test
    - name: 'Automated Version Bump'
      if: github.event_name != 'pull_request'
      id: version-bump
      uses: 'phips28/gh-action-bump-version@master'
      with:
        tag-prefix: 'v'
        skip-tag: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Output Check'
      if: github.event_name != 'pull_request'
      env:
        NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: github.event_name != 'pull_request'
      env:
        GITHUB_REF: ${{ steps.version-bump.outputs.newTag }}
        GHR_COMPRESS: zip
        GHR_PATH: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GHR_DELETE: true
        GHR_REPLACE: true
