# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: 'Automated Version Bump'
      if: github.event_name != 'pull_request'
      id: version
      uses: 'phips28/gh-action-bump-version@master'
      with:
        tag-prefix: 'v'
        skip-tag: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'version check'
      if: github.event_name != 'pull_request'
      run: echo ${{steps.version.outputs.newTag}}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: false
    - run: npm test
    - uses: vimtor/action-zip@v1
      if: github.event_name != 'pull_request'
      with:
        files: build/ README.md
        dest: dist.zip
    - name: Upload release binaries
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            dist.zip
        tag_name: ${{steps.version.outputs.newTag}}
        release_name: cloki-view-${{steps.version.outputs.newTag}}
        draft: false
        prerelease: false
        overwrite: true
    - name: Push to Mothership
      if: github.event_name != 'pull_request'
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GH_PUSH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-directory: 'build'
        target-directory: 'view'
        target-branch: master
        destination-github-username: 'metrico'
        destination-repository-name: 'cloki'
        user-email: lorenzo.mangani@gmail.com
        commit-message: Autopublish View v${{steps.version.outputs.newTag}}
