# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: 'Automated Version Bump'
      if: github.event_name != 'pull_request'
      id: version
      uses: 'phips28/gh-action-bump-version@master'
      with:
        tag-prefix: 'v'
        skip-tag: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'version check'
      if: github.event_name != 'pull_request'
      run: echo ${{steps.version.outputs.newTag}}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: false
    - run: npm test
    - run: ls -alF
    - name: create release
      id: createrelease
      if: github.event_name != 'pull_request'
      uses: gregoranders/nodejs-create-release@v0.0.13
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{steps.version.outputs.newTag}}
        name: cloki-view-${{steps.version.outputs.newTag}} Release
        target: ${{ github.ref }}
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["./build/*"]'
        ref: ${{steps.version.outputs.newTag}}
